# Generated by Django 2.1.3 on 2019-08-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendees',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Eventid', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Isattend', models.IntegerField(default='0')),
                ('Meetingtime', models.DateTimeField()),
                ('Attendtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'attendees',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Subject', models.CharField(max_length=255)),
                ('Organizer', models.CharField(max_length=255)),
                ('Start', models.DateTimeField()),
                ('Location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Openid', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
